Refactored parsing and added help

diff --git a/bin/inplace b/bin/inplace
--- a/bin/inplace
+++ b/bin/inplace
@@ -1,23 +1,34 @@
 #!/usr/bin/env bash
-set -o errexit
-set -o nounset
-set -o pipefail
+set -o errexit -o nounset -o pipefail
+shopt -s extglob
+H='
+Usage:
+	inplace <FILE> <PROGRAM> [ARGS ...]
+Examples:
+	inplace tlds.txt tr [:lower:] [:upper:]
+';H=${H%%*([[:space:]])};H=${H##*([[:space:]])}
 
-declare FILE=
-declare FILE_TEMP=
 
-FILE=$1
-shift
-
-if ! [[ -f $FILE ]]; then
-	echo Only operates on regular files.
-	exit 1
-fi
-
+# If nothing, then do nothing?
 if [[ $# -eq 0 ]]; then
-	exit 0 #identity situation
+	exit
 fi
 
+if [[ $# -eq 1 && $1 = @(-h|--help) ]]; then
+	echo "$H"
+	exit
+fi
+
+if [[ $# -eq 1 ]]; then
+	echo "Error: program not specified" >&2
+	echo "$H" >&2
+	exit
+fi
+
+
+FILE=$1; shift
+
+FILE_TEMP=
 trap 'rm --force "$FILE_TEMP"' ERR
 FILE_TEMP=$(mktemp --quiet --tmpdir="$(dirname "$FILE")" '.inplace.XXXXXXXXXX~')
 
